resources:
- name: python-repo
  type: git
  source:
    uri: https://github.com/jagadeeschaws/snowmeta.git
    branch: dev

jobs:
- name: build-snowmeta
  plan:
  - get: python-repo
    trigger: true
  - task: build-whl
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: "3.8"  # or your desired Python version
      inputs:
      - name: python-repo
      outputs:
      - name: wheel-file
      run:
        path: sh
        args:
        - -exc
        - |
          cd python-repo
          pip install -r requirements.txt  # Install dependencies
          pip install wheel
          python setup.py sdist bdist_wheel
          cp dist/*.whl ../wheel-file/

